<?php
function catalog_seed_data() {
    return [
        'menu' => [
            ['id' => 1, 'title' => 'Головна', 'link' => 'index.php', 'sort_order' => 1],
            ['id' => 2, 'title' => 'Фільми', 'link' => 'category.php?category_id=1', 'sort_order' => 2],
            ['id' => 3, 'title' => 'Серіали', 'link' => 'category.php?category_id=2', 'sort_order' => 3],
            ['id' => 4, 'title' => 'Драми', 'link' => 'category.php?category_id=3', 'sort_order' => 4],
            ['id' => 5, 'title' => 'Бойовики', 'link' => 'category.php?category_id=4', 'sort_order' => 5],
        ],
        'categories' => [
            ['id' => 1, 'name' => 'Фільми', 'slug' => 'films', 'description' => 'Повнометражні кінофільми різних жанрів.'],
            ['id' => 2, 'name' => 'Серіали', 'slug' => 'series', 'description' => 'Багатосерійні історії для тривалого перегляду.'],
            ['id' => 3, 'name' => 'Драми', 'slug' => 'drama', 'description' => 'Сюжети з сильними емоціями та глибокими персонажами.'],
            ['id' => 4, 'name' => 'Бойовики', 'slug' => 'action', 'description' => 'Динамічні фільми з пригодами, сутичками та напругою.'],
            ['id' => 5, 'name' => 'Мультфільми', 'slug' => 'animation', 'description' => 'Анімаційні фільми та яскраві історії для різного віку.'],
        ],
        'news' => [
            ['id' => 1, 'header' => 'Дюна: Частина друга', 'content' => 'Фантастична сага про Пола Атріда, який об’єднується з фременами та проходить шлях від вигнанця до лідера. Фільм поєднує масштабні пустельні сцени, політичні інтриги та боротьбу за майбутнє планети Арракіс.', 'image' => 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 'datatime' => '2026-05-01', 'category_id' => 1, 'media_type' => 'Фільм', 'year' => 2024, 'rating' => 8.5, 'director' => 'Дені Вільнев', 'country' => 'США, Канада', 'duration' => '2 год 46 хв', 'trailer' => 'https://www.youtube.com/watch?v=Way9Dexny3w', 'featured' => 1],
            ['id' => 2, 'header' => 'Інтерстеллар', 'content' => 'Науково-фантастична історія про групу дослідників, які вирушають крізь космічну червоточину, щоб знайти новий дім для людства. Картина піднімає теми родини, часу, відповідальності та виживання.', 'image' => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'datatime' => '2026-05-02', 'category_id' => 1, 'media_type' => 'Фільм', 'year' => 2014, 'rating' => 8.7, 'director' => 'Крістофер Нолан', 'country' => 'США, Велика Британія', 'duration' => '2 год 49 хв', 'trailer' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E', 'featured' => 1],
            ['id' => 3, 'header' => 'Оппенгеймер', 'content' => 'Біографічна драма про Дж. Роберта Оппенгеймера та створення атомної бомби. Фільм показує складний вибір ученого, наукові відкриття, політичний тиск і наслідки, які змінили світ.', 'image' => 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 'datatime' => '2026-05-03', 'category_id' => 3, 'media_type' => 'Фільм', 'year' => 2023, 'rating' => 8.1, 'director' => 'Крістофер Нолан', 'country' => 'США, Велика Британія', 'duration' => '3 год', 'trailer' => 'https://www.youtube.com/watch?v=uYPbbksJxIg', 'featured' => 0],
            ['id' => 4, 'header' => 'Бетмен', 'content' => 'Темна детективна історія про молодого Брюса Вейна, який розслідує серію злочинів у Ґотемі. Фільм робить акцент на атмосфері нуару, психології героя та корупції міста.', 'image' => 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg', 'datatime' => '2026-05-04', 'category_id' => 4, 'media_type' => 'Фільм', 'year' => 2022, 'rating' => 7.7, 'director' => 'Метт Рівз', 'country' => 'США', 'duration' => '2 год 56 хв', 'trailer' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4', 'featured' => 0],
            ['id' => 5, 'header' => 'Аватар: Шлях води', 'content' => 'Продовження історії Пандори, де родина Джейка Саллі стикається з новою загрозою та відкриває культуру морського народу. Фільм вирізняється візуальним світом, пригодами та темою захисту сім’ї.', 'image' => 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', 'datatime' => '2026-05-05', 'category_id' => 1, 'media_type' => 'Фільм', 'year' => 2022, 'rating' => 7.6, 'director' => 'Джеймс Кемерон', 'country' => 'США', 'duration' => '3 год 12 хв', 'trailer' => 'https://www.youtube.com/watch?v=d9MyW72ELq0', 'featured' => 0],
            ['id' => 6, 'header' => 'Людина-павук: Навколо всесвіту', 'content' => 'Анімаційна супергеройська пригода про Майлза Моралеса, який відкриває мультивсесвіт і зустрічає інших Людей-павуків. Мультфільм має яскравий стиль, гумор та сильну історію дорослішання.', 'image' => 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', 'datatime' => '2026-05-06', 'category_id' => 5, 'media_type' => 'Мультфільм', 'year' => 2018, 'rating' => 8.4, 'director' => 'Боб Персічетті, Пітер Ремзі, Родні Ротман', 'country' => 'США', 'duration' => '1 год 57 хв', 'trailer' => 'https://www.youtube.com/watch?v=g4Hbz2jLxvQ', 'featured' => 0],
            ['id' => 7, 'header' => 'Дивні дива', 'content' => 'Серіал про групу друзів з містечка Гокінс, які стикаються з таємничими експериментами, зникненнями та паралельним світом. Атмосфера 80-х поєднана з фантастикою, містикою і пригодами.', 'image' => 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg', 'datatime' => '2026-05-07', 'category_id' => 2, 'media_type' => 'Серіал', 'year' => 2016, 'rating' => 8.6, 'director' => 'Брати Даффер', 'country' => 'США', 'duration' => '4 сезони', 'trailer' => 'https://www.youtube.com/watch?v=b9EkMc79ZSU', 'featured' => 1],
            ['id' => 8, 'header' => 'Останні з нас', 'content' => 'Постапокаліптичний серіал про Джоела та Еллі, які подорожують небезпечними США після глобальної катастрофи. Історія поєднує виживання, драму та сильний емоційний зв’язок персонажів.', 'image' => 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg', 'datatime' => '2026-05-08', 'category_id' => 2, 'media_type' => 'Серіал', 'year' => 2023, 'rating' => 8.7, 'director' => 'Крейг Мейзін, Ніл Дракманн', 'country' => 'США, Канада', 'duration' => '1 сезон', 'trailer' => 'https://www.youtube.com/watch?v=uLtkt8BonwM', 'featured' => 1],
            ['id' => 9, 'header' => 'Венздей', 'content' => 'Комедійно-містичний серіал про Венздей Аддамс, яка навчається в академії Невермор і розслідує загадкові події. У центрі сюжету - сарказм, детектив, надприродні здібності й темна естетика.', 'image' => 'https://image.tmdb.org/t/p/w500/jeGtaMwGxPmQN5xM4ClnwPQcNQz.jpg', 'datatime' => '2026-05-09', 'category_id' => 2, 'media_type' => 'Серіал', 'year' => 2022, 'rating' => 8.1, 'director' => 'Альфред Гоф, Майлз Міллар', 'country' => 'США', 'duration' => '1 сезон', 'trailer' => 'https://www.youtube.com/watch?v=Di310WS8zLk', 'featured' => 0],
            ['id' => 10, 'header' => 'Пуститися берега', 'content' => 'Кримінальна драма про вчителя хімії Волтера Вайта, який після діагнозу змінює своє життя та входить у небезпечний світ наркобізнесу. Серіал відомий розвитком персонажів і напруженим сюжетом.', 'image' => 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg', 'datatime' => '2026-05-10', 'category_id' => 2, 'media_type' => 'Серіал', 'year' => 2008, 'rating' => 8.9, 'director' => 'Вінс Ґілліґан', 'country' => 'США', 'duration' => '5 сезонів', 'trailer' => 'https://www.youtube.com/watch?v=HhesaQXLuRY', 'featured' => 0],
            ['id' => 11, 'header' => 'Відьмак', 'content' => 'Фентезі-серіал про мисливця на монстрів Ґеральта з Рівії, чия доля пов’язана з чарівницею Йеннефер і принцесою Цірі. У проєкті є магія, битви, політика та темний фольклор.', 'image' => 'https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg', 'datatime' => '2026-05-11', 'category_id' => 2, 'media_type' => 'Серіал', 'year' => 2019, 'rating' => 8.0, 'director' => 'Лорен Шмідт Гіссріх', 'country' => 'США, Польща', 'duration' => '3 сезони', 'trailer' => 'https://www.youtube.com/watch?v=ndl1W4ltcmg', 'featured' => 0],
            ['id' => 12, 'header' => 'Дім дракона', 'content' => 'Фентезі-драма про дім Таргарієнів задовго до подій «Гри престолів». Серіал розкриває боротьбу за владу, сімейні конфлікти та політичні інтриги навколо Залізного трону.', 'image' => 'https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg', 'datatime' => '2026-05-12', 'category_id' => 2, 'media_type' => 'Серіал', 'year' => 2022, 'rating' => 8.4, 'director' => 'Раян Кондал, Джордж Р. Р. Мартін', 'country' => 'США', 'duration' => '2 сезони', 'trailer' => 'https://www.youtube.com/watch?v=DotnJ7tTA34', 'featured' => 0],
            ['id' => 13, 'header' => 'Лост', 'content' => 'Після авіакатастрофи пасажири рейсу 815 опиняються на загадковому острові. Вони намагаються вижити, знайти спосіб повернутися додому та поступово розкривають таємниці острова, які змінюють їхнє уявлення про реальність.', 'image' => 'https://image.tmdb.org/t/p/w500/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg', 'datatime' => '2026-05-13', 'category_id' => 2, 'media_type' => 'Серіал', 'year' => 2004, 'rating' => 8.3, 'director' => 'Джей Джей Абрамс, Деймон Лінделоф, Карлтон К’юз', 'country' => 'США', 'duration' => '6 сезонів', 'trailer' => 'https://www.youtube.com/watch?v=KTu8iDynwNc', 'featured' => 1],
        ],
        'episodes' => [
            ['id' => 1, 'post_id' => 13, 'season_number' => 1, 'episode_number' => 1, 'title' => 'Пілот, частина 1', 'description' => 'Початок історії: пасажири рейсу 815 прокидаються після катастрофи на невідомому острові.', 'video_url' => 'https://www.youtube.com/embed/KTu8iDynwNc'],
            ['id' => 2, 'post_id' => 13, 'season_number' => 1, 'episode_number' => 2, 'title' => 'Пілот, частина 2', 'description' => 'Герої знайомляться ближче й починають розуміти, що острів приховує небезпечні таємниці.', 'video_url' => 'https://www.youtube.com/embed/F7_dkEkE50g'],
            ['id' => 3, 'post_id' => 13, 'season_number' => 1, 'episode_number' => 3, 'title' => 'Табула Раса', 'description' => 'Перші конфлікти між вцілілими та спроби організувати життя після катастрофи.', 'video_url' => 'https://www.youtube.com/embed/x80aRLFK1x4'],
            ['id' => 4, 'post_id' => 13, 'season_number' => 1, 'episode_number' => 4, 'title' => 'Прогулянка', 'description' => 'Серія про віру, страхи та особисті таємниці одного з ключових персонажів.', 'video_url' => 'https://www.youtube.com/embed/KTu8iDynwNc'],
            ['id' => 5, 'post_id' => 13, 'season_number' => 1, 'episode_number' => 5, 'title' => 'Білий кролик', 'description' => 'Пошук відповідей на острові стає дедалі небезпечнішим і дивнішим.', 'video_url' => 'https://www.youtube.com/embed/F7_dkEkE50g'],
        ],
    ];
}
